# Generated by Django 4.0.10 on 2023-08-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_post_image_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, verbose_name='url'),
        ),
    ]
